### ISSUE TITLE
Horus Widget 1.9.4 beta1 shows only disabled (CRSF)

### ISSUE THREAD

**Issue by twistedwings** [yaapu/FrskyTelemetryScript#116] opened 2021-06-11 20:42 UTC
after upgrading from 1.8.1 the widget shows only text "disabled".

Radiomaster TX16S
OpenTX 2.3.11

**Comment by madjan06** [comment] 2021-06-15 21:33
I have the same problem.

HORUS X10S
OpenTX 2.3.1
Arduplane 4.1Beta
Crossfire 3.78

In the telemetry-widget-settings I get the following error:

refresh():?:0: attempt to perform arithmetic on field 'terrainLastData' (a nil value)

**Comment by yak-54** [comment] 2021-06-15 23:08
Try update opentx to 2.3.11 ?
opentx 2.3.1 is over 3 years old Firmware for that radio a lot of LUA changes

**Comment by madjan06** [comment] 2021-06-16 04:39
It is 2.3.10, sorry I missed a zero, it was a little bit late yesterday, but I try to update to 2.3.12 today. 
Maybe that helps

**Comment by depeurvince** [comment] 2021-06-16 05:49
I got the same problem.

Radiomaster TX16S
OpenTX 2.3.12
Arduplane 4.1Beta
Crossfire 4.11

In the telemetry-widget-settings I get the following error:

refresh():?:0: attempt to perform arithmetic on field 'terrainLastData' (a nil value)

If I delete the widget and set it again, it works but at next startup it crashes again..

Any ideas?

**Comment by yaapu** [comment] 2021-06-18 17:17
guys please try to download this dev version and let me know if it fixes the issue, simply overwrite what you have installed now thanks :-)

[SD.ZIP](https://github.com/yaapu/FrskyTelemetryScript/files/6678466/SD.ZIP)

**Comment by depeurvince** [comment] 2021-06-18 19:57
Thanks a lot, eager to try it! Unfortunately I won't be able to try before Monday. 
Wish you a nice weekend!

**Comment by madjan06** [comment] 2021-06-19 11:36
Hi,
I have tested it, but I do not know if it is behaving properly.

First try it did not work, disconnected everything from power, repowered the Horus and saw the telemtry widget, no error.
After that I powered my fc and got telemtry data and the widget worked fine. 
Then I disconnected the fc from power, the widget still worked, but as soon as I repower the fc the widget runs into the same error as before and I have to disable the widget and reenable it or restart the horus to get it working again.

If you need more Information I try my best to provide them, thanks a lot for your work ;-)

**Comment by yaapu** [comment] 2021-06-19 16:54
@madjan06 do you get

refresh():?:0: attempt to perform arithmetic on field 'terrainLastData' (a nil value)

**Comment by madjan06** [comment] 2021-06-19 17:57
> @madjan06 do you get
> 
> refresh():?:0: attempt to perform arithmetic on field 'terrainLastData' (a nil value)

Yes, exactly

**Comment by depeurvince** [comment] 2021-06-23 06:55
Hi Alex, 

I tried the dev version that you posted, the problem remain the same.
The widget crashes at every startup, right after the FC initialisation and most probably randomly during the flight.
Setting the widget again in the telemetry page makes it working until the next crash.

**Comment by yaapu** [comment] 2021-06-23 15:50
I can't crash it, which OpenTX version and which ArduPilot version?

**Comment by yaapu** [comment] 2021-06-23 15:50
frsky or crossfire?

**Comment by madjan06** [comment] 2021-06-24 05:27
@yaapu 

@depeurvince wrote a few posts above that he uses the following:
Radiomaster TX16S
OpenTX 2.3.12
Arduplane 4.1Beta
Crossfire 4.11

The only difference in my setup is, that I use a Horus x10s with OpenTX 2.3.10.

**Comment by depeurvince** [comment] 2021-06-24 08:53
Yes exactly! 
It crashed with openTX 2.3.11 as well.
I did few flights yesterday, it crashes during the flight. 
It seems that it happens when there is a change between RF mode 1 and 2 but difficult to say while piloting..

**Comment by yaapu** [comment] 2021-06-24 09:07
ok, guys sorry for not reading the whole thread :-)

**Comment by depeurvince** [comment] 2021-06-24 09:32
No worries 😉

**Comment by yaapu** [comment] 2021-06-24 20:14
I've found the bug :-) fix is coming

**Comment by yaapu** [comment] 2021-06-24 20:20
please try this version and thanks for the feedback!

[SD.ZIP](https://github.com/yaapu/FrskyTelemetryScript/files/6711950/SD.ZIP)

**Comment by depeurvince** [comment] 2021-06-25 06:43
Great, congratulation, it seems to work!
At least no more crashes at startup, will test in flight asap and give you the feedback.

Many thanks!

**Comment by madjan06** [comment] 2021-06-25 11:57
Seems to be working for me also, great work @yaapu 😉

**Comment by yaapu** [comment] 2021-06-25 15:12
Great!

**Comment by DarkSoulRL** [comment] 2021-06-27 15:48
Yes! ty, working for me too.

**Comment by yaapu** [comment] 2021-06-27 16:22
Ok I'll close it, thanks everynody

**Closed by yaapu** 2021-06-27 16:22 UTC

**Comment by padcom** [comment] 2021-06-28 19:04
Could you update the repository with the latest sources? Maybe create a branch with the latest sources? It is really hard to check the latest code and what kind of fixes you do if the source is not published. Only `dev` and `master` branches are visible, but those are ages old. 

Pretty please?

**Comment by yaapu** [comment] 2021-06-28 20:02
Yes, the repo is a bit behind, master a lot, dev 2 months. I'll see what I can do

**Comment by padcom** [comment] 2021-06-29 20:31
@yaapu Do you think I should open the same issue for Taranis? I do get the same error, pretty much 100% of the time when I open the telemetry screen. Nothing works.

**Comment by yaapu** [comment] 2021-06-29 20:36
@padcom it's the same issue, fixed on my dev branch, need some time to publish it, sorry

**Comment by padcom** [comment] 2021-06-29 21:03
Btw, I checked the SD.zip on my Jumper T18 (otx 2.3.11) and this is what I get:

https://www.youtube.com/watch?v=s8n394-Xrks

When I try to open one of the telemetry screens I can see a brief flash as if the app would start and then the text "disabled" shows in the left-top corner of the screen. I am not receiving any data besides the last message about RC control being out.

**Comment by yaapu** [comment] 2021-07-04 09:49
> Could you update the repository with the latest sources? Maybe create a branch with the latest sources? It is really hard to check the latest code and what kind of fixes you do if the source is not published. Only `dev` and `master` branches are visible, but those are ages old.
> 
> Pretty please?

Hi repository updated, check the dev branch

**Comment by yaapu** [comment] 2021-07-04 09:52
> Btw, I checked the SD.zip on my Jumper T18 (otx 2.3.11) and this is what I get:
> 
> https://www.youtube.com/watch?v=s8n394-Xrks
> 
> When I try to open one of the telemetry screens I can see a brief flash as if the app would start and then the text "disabled" shows in the left-top corner of the screen. I am not receiving any data besides the last message about RC control being out.

better use the discuss forum I don't think this is a bug but a rather a config issue, I tried my script on the T18 in the sim and worked just fine

**Comment by padcom** [comment] 2021-07-04 11:58
@yaapu Configuration issue?! Are quite serious? An out-of-the-box Jumper T18 with just added your telemetry script with no configuration done whatsoever (besides enabling the CRSF support) can have a configuration issue?

**Comment by padcom** [comment] 2021-07-04 12:52
After reinstalling everything from the `dev` branch the problem is gone. Thanks. Will see if the bug will resurface.

**Comment by yaapu** [comment] 2021-07-04 15:49
>@yaapu Configuration issue?! Are quite serious? An out-of-the-box Jumper T18 with just added your telemetry script with no configuration done whatsoever (besides enabling the CRSF support) can have a configuration issue?

as strange as it may sound too many times (hundreds) it turned out to be some sort of user config issue, as trivial as forgetting to eject the SD and corrupting some files, so my first advice is always double check everything especially because such a big bug as not working on a clean install would have raised so many issue request that in no way it would have gone unnoticed, anyway glad you had it working
